- World:
    name: world
    lines:
      - [  0,  0, 17,  0 ]
      - [ 17,  0, 17, 14 ]
      - [ 17, 14,  0, 14 ]
      - [  0, 14,  0,  0 ]
      
      - [  2,  2,  5,  2 ]
      - [  5,  2,  5,  4 ]
      - [  5,  4,  2,  4 ]
      - [  2,  4,  2,  2 ]

      - [  2,  6,  5,  6 ]
      - [  5,  6,  5,  8 ]
      - [  5,  8,  2,  8 ]
      - [  2,  8,  2,  6 ]

      - [  2, 10,  5, 10 ]
      - [  5, 10,  5, 12 ]
      - [  5, 12,  2, 12 ]
      - [  2, 12,  2, 10 ]
      
      - [  7,  2, 10,  2 ]
      - [ 10,  2, 10,  4 ]
      - [ 10,  4,  7,  4 ]
      - [  7,  4,  7,  2 ]

      - [  7,  6, 10,  6 ]
      - [ 10,  6, 10,  8 ]
      - [ 10,  8,  7,  8 ]
      - [  7,  8,  7,  6 ]

      - [  7, 10, 10, 10 ]
      - [ 10, 10, 10, 12 ]
      - [ 10, 12,  7, 12 ]
      - [  7, 12,  7, 10 ]
      
      - [ 12,  2, 15,  2 ]
      - [ 15,  2, 15,  4 ]
      - [ 15,  4, 12,  4 ]
      - [ 12,  4, 12,  2 ]

      - [ 12,  6, 15,  6 ]
      - [ 15,  6, 15,  8 ]
      - [ 15,  8, 12,  8 ]
      - [ 12,  8, 12,  6 ]

      - [ 12, 10, 15, 10 ]
      - [ 15, 10, 15, 12 ]
      - [ 15, 12, 12, 12 ]
      - [ 12, 12, 12, 10 ]
      

- Plugin:
    name: vasco
    spec: vasco-plugin

- VascoRobot:
    name: vasco
    scan_topic: vasco/scan
    pose: [ 1, 1, 0 ]
    sd_max: 2.0
    goals:
      - [  1,  1,  0,  0.1, 3.2 ]
      - [ 16,  1,  0,  0.1, 3.2 ]
      - [ 16,  5,  0,  0.1, 3.2 ]
      - [  1,  5,  0,  0.1, 3.2 ]
      - [  1,  9,  0,  0.1, 3.2 ]
      - [ 16,  9,  0,  0.1, 3.2 ]
      - [ 16,  13,  0,  0.1, 3.2 ]
      - [  1,  13,  0,  0.1, 3.2 ]
    noisy_scanners: true
#    scanner_noise_min_factor:  0.9
#    scanner_noise_max_factor:  1.1
    scanner_noise_min_offset: -0.01
    scanner_noise_max_offset:  0.01

- View:
    name: ground-truth
    camera:  world
    drawings:
      - world
      - vasco_true_drawing
      - vasco_lidar
    window: [ 0.0,  0.0,  1.0,  1.0 ]
    border:  0
